<?php
/**
 * @var \Adaptis\Payment\Block\Checkout\Form $block
 */
?>
<h1><?= __('Redirecting to Adaptis') ?></h1>
<p><?= __('Processing, please wait. Do not click refresh/back button or this transaction may be interrupted or terminated.') ?></p>
<form
  id="adaptis-payment-checkout-form"
  method="post"
  action="<?= $block->escapeUrl($block->getHostedPaymentUrl()) ?>"
>
    <input type="hidden" name="MerchantCode" value="<?= $block->escapeHtmlAttr($block->getMerchantCode()) ?>">
    <input type="hidden" name="RefNo" value="<?= $block->escapeHtmlAttr($block->getRefNo()) ?>">
    <input type="hidden" name="RequestType" value="10">
    <input type="hidden" name="Amount" value="<?= $block->escapeHtmlAttr($block->getAmount()) ?>">
    <input type="hidden" name="Currency" value="<?= $block->escapeHtmlAttr($block->getCurrency()) ?>">
    <input type="hidden" name="ProdDesc" value="<?= $block->escapeHtmlAttr($block->getProdDesc()) ?>">
    <input type="hidden" name="Name" value="<?= $block->escapeHtmlAttr($block->getUserName()) ?>">
    <input type="hidden" name="Email" value="<?= $block->escapeHtmlAttr($block->getUserEmail()) ?>">
    <input type="hidden" name="ContactNumber" value="<?= $block->escapeHtmlAttr($block->getUserContact()) ?>">
    <input type="hidden" name="BillingAddressLine1" value="<?= $block->escapeHtmlAttr($block->getStreet()) ?>">
    <!-- optional -->
    <input type="hidden" name="BillingAddressLine2" value=""> 
    <input type="hidden" name="BillingAddressLine3" value="">
    <input type="hidden" name="BillingAddressState" value="<?= $block->escapeHtmlAttr($block->getState()) ?>">
    <input type="hidden" name="BillingAddressCity" value="<?= $block->escapeHtmlAttr($block->getCity()) ?>">
    <input type="hidden" name="BillingAddressPostalCode" value="<?= $block->escapeHtmlAttr($block->getPostalCode()) ?>">
    <input type="hidden" name="BillingAddressCountry" value="<?= $block->escapeHtmlAttr($block->getCountry()) ?>">
    <input type="hidden" name="SignatureType" value="<?= $block->escapeHtmlAttr($block->getSignatureType()) ?>">
    <input type="hidden" name="Signature" value="<?= $block->escapeHtmlAttr($block->getSignature()) ?>">
    <input type="hidden" name="ResponseURL" value="<?= $block->escapeUrl($block->getResponseUrl()) ?>">
    <input type="hidden" name="BackendURL" value="<?= $block->escapeUrl($block->getBackendUrl()) ?>">
    <input type="hidden" name="PaymentId" value="<?= $block->escapeHtmlAttr($block->getPaymentId()) ?>">
</form>
<script>
  (function (){
    const $form = window.document.getElementById('adaptis-payment-checkout-form')
    $form.submit()
  })()
</script>
